name: MGMA
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - fastp
  - bwa
  - samtools
  - bedtools
  - mosdepth
  - bioconda::unicycler
  - quast
  - ca-certificates
  - openssl
  - prokka
  - certifi
  - bioconda::mummer
  - bioconda::qualimap
